name: PlayerSizer
version: 1.1.1
author: Matthww
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
description: Shows info about a certain player!
main: Matthww\PlayerSizer\PlayerSizer

commands:
 size:
  description: Sets the size of a player!
  usage: "/size <player> <size>"
  permission: playersizer.use
  aliases: ['scale']
permissions:
  size:
    default: false
    children:
      playersizer.use:
        default: op
        description: "Allows the user to run the size command!"
      playersizer.other:
        default: op
        description: "Allows the user to resize other players!"
